@startuml
hide empty description

skinparam shadowing            true
skinparam ArrowFontColor       #bbb
skinparam ArrowFontStyle       italic
skinparam ArrowColor           blue
skinparam ArrowThickness       0.3
skinparam StateFontColor       blue
skinparam StateBackgroundColor lightblue
skinparam StateBorderColor     blue
skinparam StateBorderThickness 2

title "WebSocketClientServer\nState Machine"

state "server wannabe" as server_wannabe
state "start server"   as start_server
state "server"         as server
state "address in use" as address_in_use
state "server failed"  as server_failed
state "client wannabe" as client_wannabe
state "connect client" as connect_client
state "client"         as client
state "client failed"  as client_failed

[*]            -->              server_wannabe
server_wannabe -[thickness=5]-> start_server   : cleanup, start server,  → server
start_server   -[thickness=2]-> address_in_use
start_server   -[thickness=2]-> server_failed
start_server   -[thickness=5]-> server         : hook up server event listeners
server         -[thickness=2]-> server_failed
address_in_use -[thickness=2]-> client_wannabe
server_failed  -[thickness=2]-> client_wannabe
client_wannabe -->              connect_client : start connecting
connect_client -->              client         : connected
connect_client -->              client_failed  : could not
client         -[thickness=2]-> client_failed
client_failed  -->              server_wannabe
@enduml