@startuml
hide empty description

skinparam shadowing            true
skinparam ArrowFontColor       #bbb
skinparam ArrowFontStyle       italic
skinparam ArrowColor           blue
skinparam ArrowThickness       0.3
skinparam StateFontColor       blue
skinparam StateBackgroundColor lightblue
skinparam StateBorderColor     blue
skinparam StateBorderThickness 2

title "WebSocketClientServer\nState Machine"

state "server wannabe" as server_wannabe
state "start server"   as start_server
state "server"         as server
state "address in use" as address_in_use
state "server closed"  as server_closed
state "client wannabe" as client_wannabe
state "connect client" as connect_client
state "client"         as client
state "client closed"  as client_closed
state "closed"         as closed

[*]            -->                     server_wannabe
server_wannabe -[thickness=5]->        start_server   : cleanup, start server,  → server
server_wannabe -[dotted,thickness=5]-> closed         : close
start_server   -[thickness=2]->        address_in_use
start_server   -[thickness=2]->        server_closed
start_server   -[thickness=5]->        server         : send outgoing messages
start_server   -[dotted,thickness=5]-> closed         : close
server         -[thickness=2]->        server_closed
server         -[dotted,thickness=5]-> closed         : close
address_in_use -[thickness=2]->        client_wannabe
address_in_use -[dotted,thickness=5]-> closed         : close
server_closed  -[thickness=2]->        client_wannabe
server_closed  -[dotted,thickness=5]-> closed         : close
client_wannabe -[thickness=5]->        connect_client : cleanup, start connecting
client_wannabe -[dotted,thickness=5]-> closed         : close
connect_client -[thickness=5]->        client         : send outgoing messages
connect_client -[thickness=2]->        client_closed
connect_client -[dotted,thickness=5]-> closed         : close
client         -[thickness=2]->        client_closed
client         -[dotted,thickness=5]-> closed         : close
client_closed  -[thickness=2]->        server_wannabe
client_closed  -[dotted,thickness=5]-> closed         : close
closed         -[dotted]->             closed         : already closed
closed         -[dotted]->             [*]
@enduml